version: '3.7'

services:
  db:
    image: kartoza/postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=agricom
    ports:
      - "25432:25432"
    networks:
      - main
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    networks:
      - main
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  main:
    external: true 